package no.nav.amt.person.service.nav_bruker

enum class InnsatsgruppeV1 {
	STANDARD_INNSATS,
	SITUASJONSBESTEMT_INNSATS,
	SPESIELT_TILPASSET_INNSATS,
	GRADERT_VARIG_TILPASSET_INNSATS,
	VARIG_TILPASSET_INNSATS,
}

enum class Innsatsgruppe {
	GODE_MULIGHETER,
	TRENGER_VEILEDNING,
	TRENGER_VEILEDNING_NEDSATT_ARBEIDSEVNE,
	JOBBE_DELVIS,
	LITEN_MULIGHET_TIL_A_JOBBE
}
